platform :ios, '10.0'
use_frameworks!

target 'Sainath' do
    pod 'Alamofire', '~> 4.0'
    pod 'PKHUD', '~> 5.0'
end

target 'SainathTests' do
    pod 'Alamofire', '~> 4.0'
    pod 'PKHUD', '~> 5.0'
end
